version: 'v001'

services:
  redis:
    image: redis:latest
    container_name: user-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - user-net

  postgres:
    image: postgres:14
    container_name: user-postgres
    environment:
      POSTGRES_USER: ${USERNAME_POSTGRES}
      POSTGRES_PASSWORD: ${PASSWORD_POSTGRES}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    env_file:
      - .env
    ports:
      - "5434:5432"
    networks:
      - user-net

networks:
  user-net:
    driver: bridge