version: 'v001'

services:
  redis:
    image: redis:latest
    container_name: user-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - user-net

networks:
  user-net:
    driver: bridge