spring:
  application:
    name:
      user-service
  datasource:
    username: ${USERNAME_POSTGRES}
    password: ${PASSWORD_POSTGRES}
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5434/${POSTGRES_DB}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: 0
      lettuce:
        pool:
          enabled: true
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
        shutdown-timeout: 100ms

server:
  port: 8082

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

